### ISSUE TITLE
formset bug

### ISSUE THREAD

**Issue by hampsterx** [OohlaLabs/django-silhouette#6]
using the formset tag causes the "form" variable to be blasted over with the formset.

Eg

```
{% formset inlines.0 %}

 here: [{{ form.instance.pk }}]
```
Form.instance no longer exists because form variable got replaced with formset :(

formsets/formset.html

```
 {% for form in formset %}
        {% block fields %}
            {% form_fields form %}
        {% endblock %}
```

Replacing with

```
 {% for form in formset %}
        {% block fields %}
            {{ form }}
        {% endblock %}
```

Causes the correct behaviour as this bypasses using form_fields tag which is updating the "form" context.

Not sure what the actual fix is tho :(

Cheers, TIM

**Comment by jthi3rry** [comment]
Hi Tim,

I completed the unit tests and found a bug with the part that cleaned the context after rendering a tag (it was only partially cleaned as tags pushed two dictionaries to the context but popped only one of them on exit: https://github.com/OohlaLabs/django-silhouette/commit/afacd092a2f889c28b59374018f562015da00506#diff-7aeb0ef694b8a53a14f82de9233606d6L52).

It should be fixed now if you want to give it a try.

Cheers
